export { default as Scrollbar } from './scrollbar/scrollbar.vue'
export { default as Header } from './header/header.vue'
export { default as Tabs } from './Tabs/Tabs.vue'
export { default as TabPane } from './TabPane/TabPane.vue'
export { default as CarouselMap } from './CarouselMap/CarouselMap.vue'
export { default as Footer } from './Footer/Footer.vue'